import { ArticleType } from '@/types';

export const BRAND = {
  name: 'BanPham.Com',
  slogan: 'Cứ đi rồi sẽ đến',
  email: 'hi@banpham.com',
  phone: '0972.829.205',
};

export const COLORS = {
  primary: '#F7C600',
  background: '#0D0D0D',
  text: '#FFFFFF',
  border: '#333333',
  success: '#22C55E',
  warning: '#EAB308',
  error: '#EF4444',
};

export const WORD_COUNT_REQUIREMENTS: Record<ArticleType, number> = {
  destination: 1500,
  food: 1200,
  guide: 1500,
  review: 1000,
  news: 500,
  product: 800,
  faq: 600,
  video: 300,
  article: 1200,
};

export const POWER_WORDS = [
  'top',
  'best',
  'hướng dẫn',
  'cách',
  'bí quyết',
  'mẹo',
  'review',
  'đánh giá',
  'kinh nghiệm',
  'chi tiết',
  'đầy đủ',
  'mới nhất',
  '2024',
  '2025',
  'hot',
  'trending',
  'miễn phí',
  'free',
  'giá rẻ',
  'khuyến mãi',
  'ưu đãi',
  'sale',
  'giảm giá',
];

export const CTA_WORDS = [
  'xem ngay',
  'tìm hiểu',
  'khám phá',
  'đọc thêm',
  'click',
  'nhấn',
  'đăng ký',
  'liên hệ',
  'mua ngay',
  'đặt hàng',
  'tải về',
  'download',
  'bắt đầu',
  'trải nghiệm',
];

export const STOP_WORDS = [
  'va',
  'và',
  'cua',
  'của',
  'de',
  'để',
  'den',
  'đến',
  'la',
  'là',
  'cho',
  'voi',
  'với',
  'trong',
  'ngoai',
  'ngoài',
  'tren',
  'trên',
  'duoi',
  'dưới',
  'the',
  'a',
  'an',
  'and',
  'or',
  'but',
  'in',
  'on',
  'at',
  'to',
  'for',
];

export const GEO_KEYWORDS = [
  'tại',
  'ở',
  'quận',
  'huyện',
  'phường',
  'xã',
  'thành phố',
  'tỉnh',
  'đường',
  'phố',
  'ngõ',
  'hẻm',
  'số',
  'địa chỉ',
];

export const CONCLUSION_HEADINGS = [
  'tóm lại',
  'kết luận',
  'tổng kết',
  'lời kết',
  'kết bài',
  'cuối cùng',
  'summary',
  'conclusion',
];

export const PAA_PATTERNS = [
  'làm sao',
  'làm thế nào',
  'tại sao',
  'vì sao',
  'là gì',
  'như thế nào',
  'bao nhiêu',
  'khi nào',
  'ở đâu',
  'có nên',
  'nên hay không',
  'what is',
  'how to',
  'why',
  'when',
  'where',
];

export const TRUSTED_DOMAINS = [
  '.gov',
  '.edu',
  'wikipedia.org',
  'vnexpress.net',
  'tuoitre.vn',
  'thanhnien.vn',
  'dantri.com.vn',
  'zingnews.vn',
  'kenh14.vn',
  'baomoi.com',
  'who.int',
  'cdc.gov',
  'bbc.com',
  'reuters.com',
  'nytimes.com',
  'forbes.com',
  'statista.com',
];

export const BAD_ANCHOR_TEXTS = [
  'click đây',
  'click here',
  'bấm đây',
  'xem tại đây',
  'tại đây',
  'here',
  'this',
  'link',
  'read more',
  'more',
];

export const ARTICLE_TYPE_PATTERNS: Record<ArticleType, string[]> = {
  destination: ['du-lich', 'travel', 'tour', 'dia-diem', 'kham-pha', 'destination'],
  food: ['am-thuc', 'food', 'quan-an', 'nha-hang', 'mon-an', 'recipe', 'cong-thuc'],
  guide: ['huong-dan', 'guide', 'cach', 'how-to', 'tutorial', 'tips'],
  review: ['review', 'danh-gia', 'trai-nghiem', 'cam-nhan'],
  news: ['news', 'tin-tuc', 'su-kien', 'event', 'thong-bao'],
  product: ['san-pham', 'product', 'mua', 'gia', 'price'],
  faq: ['faq', 'hoi-dap', 'cau-hoi', 'q-a', 'question'],
  video: ['video', 'clip', 'youtube', 'watch'],
  article: [],
};

export const LIST_HEADING_PATTERNS = [
  /^top\s*\d+/i,
  /^\d+\s*(điều|cách|bước|mẹo|lý do|lợi ích)/i,
  /^các\s*bước/i,
  /^danh\s*sách/i,
  /^những/i,
  /^các\s*(điều|cách|mẹo|lý do)/i,
];
